# Rule Engine Configuration
# 
# This file defines all business rules for automated SMS processing.
# Rules are evaluated in order, and matched rules execute their actions.
#
# Rule Structure:
#   - name: Unique rule identifier
#   - enabled: true/false to enable/disable the rule
#   - description: Human-readable purpose
#   - conditions: List of conditions (ALL must pass - AND logic)
#   - actions: List of actions to execute (in order)

rules:
  # Rule 1: New Booking Confirmation
  # When: A new booking is detected (not in database)
  # Actions: Create DB record, send confirmation SMS
  # AC1, AC2, AC3, AC4, AC8
  - name: "New Booking Confirmation"
    description: "Send confirmation SMS to new bookings"
    enabled: true
    conditions:
      - type: "booking_not_in_db"
        params: {}
    actions:
      - type: "create_db_record"
        params: {}
      - type: "send_sms"
        params:
          template: "confirmation"

  # Rule 2: Two Hour Reminder
  # When: Booking is within 2 hours AND reminder SMS not sent yet
  # Actions: Send reminder SMS, update flag
  # AC3, AC4, AC5, AC6, AC8
  - name: "Two Hour Reminder"
    description: "Send guide SMS 2 hours before reservation"
    enabled: true
    conditions:
      - type: "time_before_booking"
        params:
          hours: 2
      - type: "flag_not_set"
        params:
          flag: "remind_sms"
    actions:
      - type: "send_sms"
        params:
          template: "guide"
          store_specific: true
      - type: "update_flag"
        params:
          flag: "remind_sms"
          value: true

  # Rule 3: Evening Event SMS
  # When: It's 8 PM AND booking is completed AND option SMS not sent AND booking has options
  # Actions: Send event SMS, update flag
  # AC3, AC4, AC5, AC8
  - name: "Evening Event SMS"
    description: "Send event SMS at 8 PM for completed bookings with options"
    enabled: true
    conditions:
      - type: "current_hour"
        params:
          hour: 20
      - type: "booking_status"
        params:
          status: "RC08"
      - type: "flag_not_set"
        params:
          flag: "option_sms"
      - type: "has_option_keyword"
        params: {"keywords": ["네이버", "인스타", "전문가 보정"]}
    actions:
      - type: "send_sms"
        params:
          template: "event"
      - type: "update_flag"
        params:
          flag: "option_sms"
          value: true

  # ============================================================================
  # Story 6.1: Example Rules from Korean Requirements
  # ============================================================================

  # Rule 4: Expert Correction Slack Digest
  # Requirement: When bookings contain "전문가 보정" keyword, dispatch daily digest to operations team
  # Implemented via: has_option_keyword condition + send_slack action
  # Reference: docs/epics/epic-6-post-mvp-enhancements.md#example-rules-from-requiermentmd-korean-requirements
  - name: "Expert Correction Slack Digest"
    description: "Send daily digest of expert correction requests to operations team"
    enabled: true
    conditions:
      - type: "has_option_keyword"
        params:
          keywords: ["전문가 보정"]
    actions:
      - type: "send_slack"
        params:
          template_name: "expert_correction_digest"
          channel: "C09N3JCA800"
          template_params:
            bookings: "{{ bookings_with_expert_correction }}"

  # Rule 5: Holiday Event Customer List
  # Requirement: During holiday/event periods, collect customers with multiple options for targeted marketing
  # Implemented via: date_range + has_multiple_options conditions + send_slack action
  # Reference: docs/epics/epic-6-post-mvp-enhancements.md#example-rules-from-requiermentmd-korean-requirements
  - name: "Holiday Event Customer List"
    description: "Collect customers with multiple options during holiday/event periods for marketing campaigns"
    enabled: false
    conditions:
      - type: "date_range"
        params:
          start_date: "2025-12-20"
          end_date: "2025-12-31"
      - type: "has_multiple_options"
        params:
          keywords: ["인스타", "네이버"]
          min_count: 1
    actions:
      - type: "send_slack"
        params:
          template_name: "holiday_event_customer_list"
          channel: "#naver_sms_auto_notify"
          template_params:
            bookings: "{{ bookings_in_date_range }}"
