sms_confirmation:
  text: |
    예약 확인 문자 발송 완료 {{ customer_name }}, {{ customer_phone }}
  parse_mode: "Markdown"

sms_detail_guide:
  text: |
    상세 안내 문자 발송 완료 {{ customer_name }}, {{ customer_phone }}
  parse_mode: "Markdown"

review_reminder:
  text: |
    리뷰 요청 문자 발송 완료 {{ customer_name }}, {{ customer_phone }}
  parse_mode: "Markdown"

daily_sms_summary:
  text: |
    [SUMMARY] 오늘 처리된 문자 {{ total_sms }}건
    성공: {{ success_count }}건 / 실패: {{ failure_count }}건
  parse_mode: "Markdown"

error_alert:
  text: |
    [ALERT] SMS 전송 실패 감지
    {{ customer_name }}
    사유: {{ reason }}
