name: rule-engine-tests

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"
      - "requirements.txt"
      - ".bandit"
      - "VALIDATION.md"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"
      - "requirements.txt"
      - ".bandit"
      - "VALIDATION.md"

jobs:
  rule-engine-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit, integration, and regression tests with coverage
        run: |
          pytest tests --cov=src/rules --cov-report=term-missing --cov-fail-under=80

      - name: Run Bandit security scan
        env:
          MOCK_AWS: ""
          AWS_PROFILE: ""
        run: |
          unset MOCK_AWS
          unset AWS_PROFILE
          bandit -c .bandit --severity-level medium --confidence-level medium -r src
